/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtmifyRouteImport } from './routes/utmify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MinhasComprasRouteImport } from './routes/minhas-compras'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'

const UtmifyRoute = UtmifyRouteImport.update({
  id: '/utmify',
  path: '/utmify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasComprasRoute = MinhasComprasRouteImport.update({
  id: '/minhas-compras',
  path: '/minhas-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utmify': typeof UtmifyRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utmify': typeof UtmifyRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/utmify': typeof UtmifyRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/minhas-compras'
    | '/sitemap.xml'
    | '/utmify'
    | '/checkout/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/minhas-compras'
    | '/sitemap.xml'
    | '/utmify'
    | '/checkout/$planId'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/minhas-compras'
    | '/sitemap.xml'
    | '/utmify'
    | '/checkout/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  MinhasComprasRoute: typeof MinhasComprasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UtmifyRoute: typeof UtmifyRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utmify': {
      id: '/utmify'
      path: '/utmify'
      fullPath: '/utmify'
      preLoaderRoute: typeof UtmifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-compras': {
      id: '/minhas-compras'
      path: '/minhas-compras'
      fullPath: '/minhas-compras'
      preLoaderRoute: typeof MinhasComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  MinhasComprasRoute: MinhasComprasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UtmifyRoute: UtmifyRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
